### PR TITLE
Add Macedonian language

### PR DESCRIPTION
**Pull request by krisfremen**
I requested a few times for Macedonian to be added on Weblate. It's been a while, so I'm making a PR to add it and start translating on Weblate.

Thanks!

### CODE REVIEW

**Comment by ibennetch** [comment]
Hi,

Wow, that must have been frustrating for you. I remember seeing the request
come through and thought it had been added. I’m sorry for the hassle you’re
going through and I appreciate you sticking with it.

We’ll take a look at this, thank you.

**Comment by williamdes** [comment]
Hi,
I did see requests to add languages but never had an UI to accept them on Weblate on the link I received by email

/cc @nijel

**Comment by krisfremen** [comment]
No worries, things do slip through the cracks sometimes :)

**Comment by ibennetch** [comment]
Merged, thank ou for your work on this!

**Comment by krisfremen** [comment]
> Merged, thank ou for your work on this!

Thank you for merging it in! I will start on the translations soon!

**Pull request merged**
