### PR TITLE
Typo corrected (German)

### PR DESCRIPTION
**Pull request by GeniusTimo**

### CODE REVIEW

**Comment by williamdes** [comment]
Hi @GeniusTimo could you fix it on [Weblate, link to translation](https://hosted.weblate.org/translate/phpmyadmin/documentation/de/?q=+source%3A%3D%22Themes+are+configured+with+%3Aconfig%3Aoption%3A%60%24cfg%5B%27ThemeManager%27%5D%60+and+%3Aconfig%3Aoption%3A%60%24cfg%5B%27ThemeDefault%27%5D%60.++Under+%3Afile%3A%60.%2Fthemes%2F%60%2C+you+should+not+delete+the+directory+%60%60pmahomme%60%60+or+its+underlying+structure%2C+because+this+is+the+system+theme+used+by+phpMyAdmin.+%60%60pmahomme%60%60+contains+all+images+and+styles%2C+for+backwards+compatibility+and+for+all+themes+that+would+not+include+images+or+css-files.++If+%3Aconfig%3Aoption%3A%60%24cfg%5B%27ThemeManager%27%5D%60+is+enabled%2C+you+can+select+your+favorite+theme+on+the+main+page.+Your+selected+theme+will+be+stored+in+a+cookie.%22+&checksum=&offset=) please

**Comment by GeniusTimo** [comment]
[Done ](https://hosted.weblate.org/translate/phpmyadmin/documentation/de/?checksum=9f8061fcba3bf6a2) ✔️

**Comment by ibennetch** [comment]
Thank you!

**Comment by williamdes** [comment]
Thank you 
Done as c6decbf2c835b1545faf0e5f8877361bcfb7c2e2

**Pull request closed without merging**
