### PR TITLE
Corrected to pt-PT instead of pt-BR

### PR DESCRIPTION
**Pull request by salvadord18**

### CODE REVIEW

**Comment by williamdes** [comment]
Hi @SalvadorD18 
I did an octopus merge, but please do not open so much PRs anymore: you can do all your work in one PR and then we will merge it.
Anyway this was a once in a lifetime merge 😄 
image

**Comment by salvadord18** [comment]
Hi @williamdes 

I'm sorry for that, I realized it when I was already finishing. It'll never happen again!! 😅

Thank you for all!

**Comment by williamdes** [comment]
Thank you for helping translating phpMyAdmin !

**Comment by salvadord18** [comment]
You're welcome!

**Pull request merged**
